version: "3.8"

services:

  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autoatendimento
    ports:
      - 5432:5432
    volumes:
      - ./infra-local/sql/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  autoatendimento:
    image: arthurgabriel73/autoatendimento:2.0
    depends_on:
      - postgres
    environment:
      - DATASOURCE_URL=postgres
    ports:
      - 8080:8080
